### ISSUE TITLE
environment.yml file location

### ISSUE THREAD

**Issue by W4RJ4** [CBIIT/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Multi-tasking-Predictor#1]
Hi, i couldn't find environment.yml file in this repository.
Can you, please, point me where i can find this file?
Thank you

**Comment by jonesse3** [comment]
Hi @W4RJ4, I added the [environment.yml](https://github.com/CBIIT/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Predictor-Multi-tasking/blob/master/Pilot1/UnoMT/environment.yml). Let me know if you have any issues. Thank you for letting us know that this file was missing.
